//! Protobuf 代码生成。
//!
//! 编译 `../../proto/*.proto` 下全部 .proto 文件，
//! 并写一个 `OUT_DIR/generated/mod.rs` 把生成的代码统一 `include!`，
//! 由 `src/proto/mod.rs` 拉入 crate。
//!
//! ## 模块结构（关键）
//!
//! prost-build 生成的 .rs 文件中，跨包引用使用 `super::xxx` 或 `super::super::xxx`
//! 相对路径。**模块嵌套结构必须与 proto package 结构对齐**，否则编译失败：
//!
//! - `OUT_DIR/corepb.rs`（package = `corepb`）→ `pub mod corepb { ... }`（在 `generated` 直属）
//! - `OUT_DIR/gatepb.rs`（package = `gatepb`）→ `pub mod gatepb { ... }`（在 `generated` 直属）
//! - `OUT_DIR/gamepb.acepb.rs`（package = `gamepb.acepb`）→
//!   `pub mod gamepb { pub mod acepb { ... } }`（嵌套在 `gamepb` 下）
//!
//! 这样从 `gamepb::acepb` 内部 `super::super::corepb` 就能解析到
//! `crate::proto::generated::corepb`，与 prost-build 内部预期一致。

use std::collections::BTreeMap;
use std::ffi::OsStr;
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};

fn main() -> io::Result<()> {
    println!("cargo:rerun-if-changed=../../proto");
    println!("cargo:rerun-if-changed=build.rs");

    let manifest_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let proto_dir = manifest_dir
        .parent()
        .and_then(Path::parent)
        .map_or_else(|| Path::new("proto").to_path_buf(), |p| p.join("proto"));

    let proto_files: Vec<PathBuf> = fs::read_dir(&proto_dir)?
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| p.extension().is_some_and(|ext| ext == "proto"))
        .collect();

    if proto_files.is_empty() {
        return Err(io::Error::new(
            io::ErrorKind::NotFound,
            format!("no .proto files found in {}", proto_dir.display()),
        ));
    }

    let mut config = prost_build::Config::new();
    config.bytes(["."]);
    config.disable_comments(&["."]);

    config.compile_protos(&proto_files, &[&proto_dir])?;

    let out_dir = std::env::var("OUT_DIR")
        .map_err(|e| io::Error::new(io::ErrorKind::NotFound, format!("OUT_DIR not set: {e}")))?;
    let out_dir = PathBuf::from(out_dir);
    let generated_dir = out_dir.join("generated");
    fs::create_dir_all(&generated_dir)?;

    // 收集所有 .rs 文件（按文件 stem 排序，目录是平铺的）
    // BTreeMap<嵌套 mod 路径, include 文件 stem>
    // 嵌套路径用 `::` 分隔，例如 "corepb" / "gamepb" / "gamepb::acepb"
    let mut modules: BTreeMap<String, String> = BTreeMap::new();
    for entry in fs::read_dir(&out_dir)? {
        let entry = entry?;
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        if path.extension() != Some(OsStr::new("rs")) {
            continue;
        }
        let stem = match path.file_stem().and_then(OsStr::to_str) {
            Some(s) => s,
            None => continue,
        };
        // 排除：自身 mod 文件
        if stem == "mod" || stem == "generated" {
            continue;
        }
        // 把文件名里的 `.` 解析为嵌套 mod 路径
        // 例如 `gamepb.acepb` → mod path `gamepb::acepb`
        let mod_path = stem.replace('.', "::");
        modules.insert(mod_path, stem.to_string());
    }

    // 写 generated/mod.rs
    // 用深度优先遍历，按嵌套层次缩进
    let mod_rs_path = generated_dir.join("mod.rs");
    let mut f = fs::File::create(&mod_rs_path)?;
    writeln!(f, "// Auto-generated by build.rs. DO NOT EDIT.")?;
    writeln!(f)?;

    // 收集所有 mod 路径，按深度排序（浅到深）
    let mut all_paths: Vec<String> = modules.keys().cloned().collect();
    all_paths.sort_by_key(|p| (p.matches("::").count(), p.clone()));

    // 按嵌套深度分层写
    let mut open_stack: Vec<(usize, String)> = Vec::new();

    for path in &all_paths {
        let segments: Vec<&str> = path.split("::").collect();
        let depth = segments.len();

        // 关闭比当前深度深的 mod
        while open_stack.len() >= depth {
            let (indent, _) = open_stack.pop().unwrap();
            write_indent(&mut f, indent)?;
            writeln!(f, "}}")?;
        }

        // 打开到当前深度的所有中间 mod（不带 include!）
        for i in open_stack.len()..depth - 1 {
            let seg = segments[i];
            let indent = i;
            write_indent(&mut f, indent)?;
            writeln!(f, "pub mod {seg} {{")?;
            open_stack.push((indent, seg.to_string()));
        }

        // 写叶子 mod（带 include!）
        let leaf_seg = segments[depth - 1];
        let leaf_indent = depth - 1;
        write_indent(&mut f, leaf_indent)?;
        writeln!(f, "pub mod {leaf_seg} {{")?;
        write_indent(&mut f, leaf_indent + 1)?;
        let stem = &modules[path];
        writeln!(f, "include!(\"../{stem}.rs\");")?;
        open_stack.push((leaf_indent, leaf_seg.to_string()));
        // 关闭叶子 mod
        write_indent(&mut f, leaf_indent)?;
        writeln!(f, "}}")?;
        open_stack.pop();
    }

    // 关闭剩余的 mod
    while let Some((indent, _)) = open_stack.pop() {
        write_indent(&mut f, indent)?;
        writeln!(f, "}}")?;
    }

    drop(f);

    println!(
        "cargo:warning=prost-build: compiled {} proto files, generated {} Rust modules (nested)",
        proto_files.len(),
        modules.len()
    );

    Ok(())
}

fn write_indent(f: &mut fs::File, level: usize) -> io::Result<()> {
    for _ in 0..level {
        write!(f, "    ")?;
    }
    Ok(())
}
